name: Build Status

on:
  push:
  pull_request:
  schedule:
    # run on sunday nights
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Test
      run: |
        python -m nose --with-coverage --cover-package ffn
    - name: Coverage
      run: |
        codecov
    # - name: Package
    #   if: startsWith(github.ref, 'refs/tags')
    #   run: |
    #     python -m pip install -U wheel
    #     python setup.py sdist
    #     python setup.py bdist_wheel

    # - name: Publish distribution 📦 to PyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     username: pmorissette
    #     password: ${{ secrets.PYPI_API_TOKEN }}
